#Activation Function


###Importing Libraries

In [1]:
from numpy import array #For Array Initialization
from numpy import random #For Randomly choosing Numbers
from numpy import dot #For Doing DOT Product
from random import choice

###Initialized Dataset

In [2]:
dataset = [
    (array([0,0,1]), 0), #array([x,y,b],e) x,y=Input , b=bias, e=Expected O/P to validate
    (array([0,1,1]), 1),
    (array([1,0,1]), 1),
    (array([1,1,1]), 1),
]
print(dataset)
print(array([0,0,1]), 0)

[(array([0, 0, 1]), 0), (array([0, 1, 1]), 1), (array([1, 0, 1]), 1), (array([1, 1, 1]), 1)]
[0 0 1] 0


###Initializing Random numbers for WEIGHTS

In [3]:
weights = random.rand(3)
weights

array([0.12815154, 0.38653116, 0.77798548])

###Initializing additional variables

In [4]:
r = 0.2 #learning Rate
n = 100 #Number of Iteration

##ACTIVATION FUNCTION

###Training & Evaluating using STEP Activation Function

In [5]:
activationFn = lambda x: 0 if x < 0 else 1 #step activation function (if i/p is negative o/p is 0 else 1)
for j in range(n):
    x, expected = choice(dataset) 
    result = dot(weights, x)
    err = expected-activationFn(result)
    weights += r * err * x

for x, _ in dataset:
    result = dot(x, weights)
    print("ResultBAFn: {} ResultAFn: {}".format(round(result,3), activationFn(result)))    

ResultBAFn: -0.022 ResultAFn: 0
ResultBAFn: 0.365 ResultAFn: 1
ResultBAFn: 0.106 ResultAFn: 1
ResultBAFn: 0.493 ResultAFn: 1


###Training & Evaluating using LINEAR Activation Function


In [6]:
activationFn = lambda x: x 

for j in range(n):
    x, expected = choice(dataset) 
    result = dot(weights, x) 
    err = expected-activationFn(result)
    weights += r * err * x

for x, _ in dataset:
    result = dot(x, weights)
    print("ResultBAFn: {} ResultAFn: {}".format(round(result,3), activationFn(result)))    

ResultBAFn: 0.292 ResultAFn: 0.29165378293815797
ResultBAFn: 0.868 ResultAFn: 0.8676676066881353
ResultBAFn: 0.661 ResultAFn: 0.6607643868982962
ResultBAFn: 1.237 ResultAFn: 1.2367782106482734


###Training & Evaluating using SIGMOID Activation Function

In [13]:
import numpy as np
activationFn = lambda x: 1/(1+np.exp(-x))
err = []
for j in range(n):
    x, expected = choice(dataset) 
    result = np.dot(weights, x) 
    error = expected - activationFn(result)
    err.append(error)  # Append the error to the list 'err'
    weights += r * error * x

for x, _ in dataset:
    result = np.dot(x, weights)
    print("ResultBAFn: {} ResultAFn: {}".format(round(result,3), activationFn(result)))


ResultBAFn: -0.638 ResultAFn: 0.3457887573920194
ResultBAFn: 1.854 ResultAFn: 0.8645768047116867
ResultBAFn: 2.223 ResultAFn: 0.9023082443318197
ResultBAFn: 4.715 ResultAFn: 0.9911159742718707


###Training & Evaluating using RELU Activation Function

In [14]:
activationFn = lambda x: 0 if x < 0 else x 
for j in range(n):
    x, expected = choice(dataset) 
    result = dot(weights, x)
    err = expected-activationFn(result)
    weights += r * err * x

for x, _ in dataset:
    result = dot(x, weights)
    print("ResultBAFn: {} ResultAFn: {}".format(round(result,3), activationFn(result)))    

ResultBAFn: -0.017 ResultAFn: 0
ResultBAFn: 0.994 ResultAFn: 0.9942940909065312
ResultBAFn: 1.0 ResultAFn: 0.9999228832433107
ResultBAFn: 2.011 ResultAFn: 2.011388782235589


###Training & Evaluating using SOFTMAX Activation Function

In [15]:
activationFn = lambda x: np.exp(x) / np.sum(np.exp(x), axis=0)
err = []
for j in range(n):
    x, expected = choice(dataset) 
    result = dot(weights, x) 
    err = expected-activationFn(result)
    error.append(err)
    weights += r * err * x

for x, _ in dataset:
    result = dot(x, weights)
    print("ResultBAFn: {} ResultAFn: {}".format(round(result,3), activationFn(result)))    

AttributeError: 'numpy.float64' object has no attribute 'append'

In [16]:
import numpy as np
activationFn = lambda x: 1 / (1 + np.exp(-x))
err = []
for j in range(n):
    x, expected = choice(dataset)
    result = np.dot(weights, x)
    error = expected - activationFn(result)
    err.append(error)  # Append the error to the list 'err'
    weights += r * error * x

for x, _ in dataset:
    result = np.dot(x, weights)
    print("ResultBAFn: {} ResultAFn: {}".format(round(result, 3), activationFn(result)))


ResultBAFn: -0.11 ResultAFn: 0.4726241020422135
ResultBAFn: 1.971 ResultAFn: 0.8776777346149318
ResultBAFn: 1.929 ResultAFn: 0.873188228044274
ResultBAFn: 4.01 ResultAFn: 0.9821839850182714
